import React from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';

// TODO: Import route tree generated by TanStack Router Vite plugin
// import { routeTree } from '../routeTree.gen';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5, // 5 minutes
      retry: 1,
    },
  },
});

// TODO: Uncomment when route tree is generated
// const router = createRouter({ routeTree, context: { queryClient } });

function App(): React.JSX.Element {
  return (
    <QueryClientProvider client={queryClient}>
      {/* TODO: Replace with <RouterProvider router={router} /> when routes are ready */}
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-primary">VidyaFlow</h1>
          <p className="mt-2 text-muted-foreground">Enterprise School Management Platform</p>
          <p className="mt-4 text-sm text-muted-foreground">
            🚀 Project scaffolding complete. Ready for development.
          </p>
        </div>
      </div>
    </QueryClientProvider>
  );
}

export default App;
